---
title: '20200420'
author: "niiiiina"
date: "2020/4/20"
output: html_document
---
```{r}
listExample <- 
  list(
    student="小明",
    `學期`=list(
      `108-1`=list(
        list(
          name="個體經濟學",
          teacher="Alice",
          grade=85
        )
      ),
      `108-2`=list(
        list(
          name="總體經濟學",
          teacher="Mark",
          grade=78
        )
      )
    )
  )
# 有多少位置可選：
length(listExample)
```

```{r}
str(listExample)
```

```{r}
listExample[[1]]
listExample[[2]]
```

```{r}
get1 <- listExample[["學期"]]# 拿出來
get1 <- listExample$`學期`# 拿出來

get2 <- listExample["學期"]# 只留下
```

```{r}
get1 # 學期拿出來，有3個元素的list
str(get1)
```

```{r}
get2 # listExample 只留下 學期元素，是個只有一個元素的list
str(get2)
```

#### get1 取出
```{r}
get1 <- listExample[["學期"]]
get1$`108-1` -> get1_layer1
str(get1_layer1)
```

```{r}
get1_layer1[[1]] -> get1_layer2
str(get1_layer2)
```

```{r}
get1_layer2$teacher
str(get1_layer2)
```


```{r}
listExample[["學期"]]$`108-1`[[1]]$teacher
```

#### get2 取出
```{r}

get2 <- listExample["學期"]
get2[[1]] -> get2_layer1 
get2_layer1[["108-1"]] -> get2_layer2
get2_layer2[[1]] -> get2_layer3
get2_layer3$teacher

```

```{r}
listExample["學期"][[1]][[1]][[1]]$teacher
#因為第一個[[1]]即等於[["學期"]]，所以多此一舉
```


##list的應用

```{r}
vector1 <- c(a=1,b=3,c=4)
vector1[["a"]]
vector1[c("a","c")]
#vector1$a
#不能用vector取錢號
```

```{r}
list1 <- list(a=1,b=3,c=4)
list1[["a"]]
list1[c("a","b")]
list1$a
```


今明兩日台北市、新北勢氣溫:
```{r}
today <- list(
  list("台北市",highest_temp = c(highest_temp = 25),lowest_temp = c(lowest_temp = 18)),
  list("新北市",highest_temp = c(highest_temp = 24),lowest_temp = c(lowest_temp = 15)))
str(today)
```

```{r}
today[[1]]$highest_temp#這個是我們命名的，下面得出來的值是vector
```


```{r}
today <- list(
  list("台北市",c(highest_temp = 25),c(lowest_temp = 18)),
  list("新北市",c(highest_temp = 24),c(lowest_temp = 15)))
str(today)
```

```{r}
today[[1]][[2]]#因為有vector所以不能用錢號
```

```{r}
tomorrow <- list(
  list("台北市",c(highest_temp = 25),c(lowest_temp = 18)),
  list("新北市",c(highest_temp = 24),c(lowest_temp = 15)))

weather <- list(today,tomorrow)

print(weather)
```

##新增/替換/刪除元素

```{r}
a <- c("1","b","TRUE")
a
a[[2]] <- "c" # 元素存在: 替換
a[[4]] <- "7" # 元素不存在： 增加
a[c(5,6)] <- c("J", "K")
a
```


```{r}
a[[7]] <- "Johnson"#要用雙引號
a

```

```{r}
a <- c(a, c("Mary"))#向量疊代
a
```


```{r}
library(lubridate)
list1 <- 
  list(
    list(
      name="Jack",
      birthday=ymd("1998-03-21"),
      status=c(height=177, weight=80)
    )
  )

str(list1)
```

```{r}
# 更改日期
list1[[1]]$birthday <- ymd("1997-03-21")

# 新增資料
list1[[2]] <- list(
  name="Mary",
  birthday=ymd("1998-08-24")
)

str(list1)
```

```{r}
list1[[2]]$status <- c(height=163, weight=45)
list1[[1]]$status[["height"]] <- 176
str(list1)
```


```{r}
list1[[1]][["age"]] <- 21# 新增
list1[[2]]["age"] <- list(21)#由於[.]會保留母層結構，所以<-右側要使用和母層相同的型態設定

# 改變「一個」時，使用[[ ]]比較不會錯。
# 用一對引號就要保留母層結構
str(list1)
```

```{r}
list1[[1]][c("bloodType","registered")] <- list("AB",TRUE)#因為是一個中括號，所以要依循母層結構來做決定

str(list1)
```

***

```{r}
listExample <- 
  list(
    student="小明",
    `學期`=list(
      `108-1`=list(
        list(
          name="個體經濟學",
          teacher="Alice",
          grade=85
        )
      ),
      `108-2`=list(
        list(
          name="總體經濟學",
          teacher="Mark",
          grade=78
        )
      )
    )
  )
# 有多少位置可選：
length(listExample)
str(listExample)
```

```{r}
listExample[[2]]$`108-1`[[2]] <- list(name = "產業經濟學")#因為是新增，所以第二個[[2]]要用2
listExample[[2]]$`108-1`[[2]][c("teacher","grade")] <- list("Wen",88)#因為有一個[]，所以依循母層結構要用list
str(listExample)
```

```{r}
print(a)
a[-c(1,3)]
a[c(-2)]


print(a)
a[-c(1,3)] -> a # 要回存才算真的刪除
```

```{r}
library(lubridate)
list1 <- 
  list(
    list(
      name="Jack",
      birthday=ymd("1998-03-21"),
      status=c(height=177, weight=80)
    ),
    list(
      name="Mary",
      birthday=ymd("1998-08-24"),
      status=c(height=163, weight=45),
      age=21,
      bloodType="AB"
    )
  )
str(list1)
```

#刪除Jack的status.
```{r}
list1[[1]][-c(3)] -> list1[[1]]#小心回存的位置
str(list1)
```


#刪除Mary的status, bloodType
```{r}
list1[[2]][-c(3,5)] -> list1[[2]]
str(list1)
```

```{r}
str(list1)
list1[[2]][c(1,2)] <- NULL#也是刪除的意思，只是不需要回存
str(list1)
```
#NULL和"-"最大的差別是"-"只能用[]，而NULL可以用[]、[[]]，$

```{r}
library(jsonlite)
fromJSON("https://data.ntpc.gov.tw/od/data/api/54DDDC93-589C-4858-9C95-18B2046CC1FC?$format=json", simplifyDataFrame = F) -> newTaipeiYouBike
```



