---
title: '20200404'
author: "niiiiina"
date: "2020/4/4"
output: html_document
---
##List

```{r}
vectorExample <- c(2, 6, 7)
listExample <- list(2, 6, 7)

print(vectorExample)
print(listExample)
```

每個元素值可以是用不同type的物件值
```{r}
#用vector儲存
#物件值都是要用相同的type,以下用雙引號將每個物件值標示為字串
c("2020-03-31T13:40:55Z",
  "一芳",
  "2",
  "水果茶")

#用list儲存
library(lubridate)
`小明交易1` <- list(
  ymd_hms("2020-03-31T13:40:55Z"), # Date/Time
  "一芳", # Character
  2, # Numeric
  "水果茶" # Character
  )
print(`小明交易1`)

```

物件值可以是vector形式，也可以list
```{r}
# 用vector
c(
  c("108學年第1學期", "高級會計學", "高等統計學"), #向量1
  c("108學年第2學期", "食在拉丁美洲") #向量2
)
```

```{r}
# 用list
list(
  c("108學年第1學期", "高級會計學", "高等統計學"), #向量1
  c("108學年第2學期", "食在拉丁美洲") #向量2
)
```

```{r}
# list含兩個vectors
`小明108學年課表A` <- list(
  c("108-1","高級會計學","高等統計學"),
  c("108-2","食在拉丁美洲")
)
print(`小明108學年課表A`)
```

```{r}
# list含兩個lists
`小明108學年課表B` <- list(
  list("108-1","高級會計學","高等統計學"),
  list("108-2","食在拉丁美洲")
  )

print(`小明108學年課表B`)
```


```{r}
# list含兩個vectors
`小明108學年課表c` <- list(
  list(
    c("108-1"),
    c("高級會計學","高等統計學")
      ),
  list(
    c("108-2"),
    c("食在拉丁美洲")
      )
                          )
print(`小明108學年課表c`)
```


物件值可以取名
```{r}
`小明108學年課表c` <- list(
  `上學期`=list(
    semester = c("108-1"),
    courses = c("高級會計學","高等統計學")
      ),
  `下學期`=list(
    semester = c("108-2"),
    courses = c("食在拉丁美洲")
      )
                          )
print(`小明108學年課表c`)
```


## Github Commit

```{r}
commit <- list(
  author = list(
    name = "Martin老師",
    email = "mtlin@gm.ntpu.edu.tw",
    time = ymd_hms("2020-03-25T07:17:40Z")
    ),
  committer = list(
    name = "emilyluckey",
    email = "emily007@gmail.com",
    time = ymd_hms("2020-03-26T08:18:40Z")
  ),
  message = "update"
)
print(commit)
```

```{r}
library(jsonlite) # 不少同學這行會有Error，還記得如何排除嗎？
toJSON(commit)
```

```{r}
library(jsonlite)
fromJSON("https://opendata.cwb.gov.tw/fileapi/v1/opendataapi/F-C0032-001?Authorization=rdec-key-123-45678-011121314&format=JSON") ->
  weather_next36hours
```

##物件儲存

```{r}
save(`小明交易1`, `小明108學年課表c`,`commit`, file = "nina.Rda")

```

```{r}
load("nina.Rda")
```

```{r}
`小明108學年第一學期` <- list(
  list(
  name = list("Alice老師"), 
  course = list("個體經濟學"), 
  score = list(85)
        ),
  list(
  name = list("Mark老師"), 
  course = list("總體經濟學"), 
  score = list(73)
  )
)
`小明108學年第二學期` <- list(
  name = list("Jason老師"), 
  course = list("作業研究"), 
  score = list(90)
)

print(`小明108學年第一學期`)
print(`小明108學年第二學期`)

```

```{r}
`小明108學年第一學期` <- list(
  list(
  name = "Alice老師", 
  course = "個體經濟學", 
  score = 85
        ),
  list(
  name = "Mark老師", 
  course = "總體經濟學", 
  score = 73
  )
)
`小明108學年第二學期` <- list(
  name = "Jason老師", 
  course = "作業研究", 
  score = 90
)

print(`小明108學年第一學期`)
print(`小明108學年第二學期`)

```

##天氣預報練習
```{r}
`天氣預報` <-list(
  `台北市` = list(
    date = c(
      today = "2020-03-31", 
      tomorrow = "2020-04-01"
    ), 
    highest = 25, 
    lowest = 18
  ), 
  `新北市` = list(
    date = c(
      today = "2020-03-31", 
      tomorrow = "2020-04-01"
    ), 
    higest = 24, 
    lowest = 15
  )
)
print(`天氣預報`)
```





